### ISSUE TITLE
Can't use /bires

### ISSUE THREAD

**Issue by cj89898** [KaiKikuchi/BetterItemRestrict#3]
Is it still being implemented?

**Comment by Bennyboy1695** [comment]
/bires isn't being registered as a command or an alias so i'd say no.
https://github.com/KaiKikuchi/BetterItemRestrict/blob/master/src/main/java/net/kaikk/mc/itemrestrict/sponge/BetterItemRestrict.java#L61 Thats the line the commands are registered on and i can't see it so maybe it was forgotten to be added.

**Comment by KaiKikuchi** [comment]
The only commands available are:
- /banneditems
- /bires reload (bukkit only)

If you want to reload the plugin on sponge, you'll have to use the Sponge built-in reload command.

**Comment by cj89898** [comment]
How do I use the config?

I tried this: `Ownership=[
 "enderio:blockWeatherObelisk|Weather Obelisk|Changes weather"
]
Usage=[]
World=[]`

But it didn't seem to work. I am on SpongeForge btw
