### ISSUE TITLE
Plugin.yml update. 

### ISSUE THREAD

**Issue by axle2005** [KaiKikuchi/BetterItemRestrict#5]
Need to update plugin.yml so it points to `net.kaikk.mc.itemrestrict.bukkit.BetterItemRestrict` instead of `net.kaikk.mc.itemrestrict.BetterItemRestrict` 

(This is just a reminder for you when you have time. )

**Comment by KaiKikuchi** [comment]
This was already fixed on local dev ages ago. Haven't pushed the latest release yet.
